-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgV+DhV/0t5ztOiuWS
mpzZoaFNrYV7E1NUtHIoUc4lCcugCgYIKoZIzj0DAQehRANCAASSiCkqUnPifK9I
ngK0NobSuY2CLYIb4TZ2P8DhrJ8AFlETbR9/2eYlTpy/8DlizWKfvhAAbUfnbhLb
7VChv5Q5
-----END PRIVATE KEY-----